services:
    nginx:
        container_name: ap-nginx
        image: 'nginx:stable-alpine'
        ports:
            - '8000:80'
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - './:/var/www/'
        depends_on:
            - mysql
            - php
    php:
        container_name: ap-php
        build:
            context: docker/dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - './:/var/www/'
    mysql:
        container_name: ap-mysql
        image: 'mysql:8.0'
        ports:
            - '3316:3306'
    composer:
        container_name: ap-composer
        build:
            context: docker/dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - './:/var/www/'
